apiVersion: v1
kind: Service
metadata:
  labels:
    app: solar-system
  name: solar-system
  namespace: _{_NAMESPACE_}_
spec:
  selector:
    app: solar-system
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80        # Public-facing port
      targetPort: 3000